# Generated by Django 3.2.12 on 2022-12-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('phone_number', models.TextField()),
                ('email', models.EmailField(max_length=40)),
                ('skills', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'CV',
                'ordering': ['birth_date'],
            },
        ),
    ]
