# Generated by Django 3.2.12 on 2022-12-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_maker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvinfo',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
