# Generated by Django 3.2.16 on 2022-12-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_maker', '0002_alter_cvinfo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvinfo',
            name='photo',
            field=models.ImageField(default=0, upload_to='photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
