# Generated by Django 3.2.16 on 2022-12-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_maker', '0003_cvinfo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvinfo',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
