# Generated by Django 3.2.16 on 2022-12-03 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_maker', '0005_cvinfo_work_expirience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cvinfo',
            old_name='work_expirience',
            new_name='work_experience',
        ),
    ]
